version: '3.8'

services:
  medplum:
    image: medplum/medplum
    restart: unless-stopped
    environment:
      - MEDPLUM_PORT=8081
      - MEDPLUM_BASE_URL=http://localhost:8081
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/medplum
      - REDIS_URL=redis://redis:6379
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=admin
    depends_on:
      - db
      - redis
    ports:
      - "8081:8081"

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medplum
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped

volumes:
  db_data:

